server:
  port: 9527
  
spring:
   application:
     name: SpringCloudTest_Zuul_Gateway
  
eureka:
  client:  #客户端注册进Eureka服务列表内
    service-url: 
      #单机版  defaultZone: http://localhost:7001/eureka
      defaultZone: http://zsc7001.com:7001/eureka,http://zsc7002.com:7002/eureka,http://zsc7003.com:7003/eureka  #集群环境
  instance:
    instance-id: gateway_9527.com  #自定义Zuul相关的服务名称信息
    prefer-ip-address: true  #访问路径可以显示IP地址
    
info:
  app.name: zsc_microservicecloud
  company.name: www.zsc.cn
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
      
zuul: 
  prefix: /zsc
  #ignored-services: "*"  #将所有的微服务名称隐藏掉
  ignored-services: springcloudtest  #将原来的服务名称隐藏掉，使得只能通过自定义的myitems路由访问服务
  routes: 
    myitems: 
      path: /myitems/**
      serviceId: springcloudtest