server: 
  port: 3344
  
spring: 
   application: 
     name: SpringCloudTest_config
   cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/Abner0421/SpringCloudTest_config.git #Github上面git仓库名字