server:
  port: 80
  
feign: 
  hystrix: 
    enabled: true
  
eureka:
  client:  #客户端注册进Eureka服务列表内
    register-with-eureka: false  #false标识不向服务中心注册自己
    service-url: 
      #单机版  defaultZone: http://localhost:7001/eureka
      defaultZone: http://zsc7001.com:7001/eureka,http://zsc7002.com:7002/eureka,http://zsc7003.com:7003/eureka  #集群环境